"""empty message

Revision ID: 56933c710155
Revises: 937b4148110b
Create Date: 2020-02-16 13:02:54.163670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56933c710155'
down_revision = '937b4148110b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Actor', 'blah')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Actor', sa.Column('blah', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
