"""empty message

Revision ID: 937b4148110b
Revises: 
Create Date: 2020-02-16 13:01:20.461618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937b4148110b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Actor', sa.Column('blah', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Actor', 'blah')
    # ### end Alembic commands ###
